### ISSUE TITLE
Keep data single precision

### ISSUE THREAD

**Issue by jvdudley** [FAIR-Universe/HEP-Challenge#126]
Some of the derived quantities are producing double precision values rather than single precision, which causes errors in some cases. Which features are doubles depends on which systematics are used. It would be good for participants if all the features had the same type. One solution would be to cast everything to a single type before it is passed to a participant's model, but it might be better to avoid increasing the precision in the intermediate steps.

**Comment by Ragansu** [comment]
The issue is being handled in PR https://github.com/FAIR-Universe/HEP-Challenge/pull/131
